In [1]:
  import numpy as np

In [2]:
a = np.array([2,4,5])
a

array([2, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [5]:
a[0]

2

In [6]:
a[2]

5

In [15]:
a2 = np.array([[2,4,5],[5,7,8]])
a2

array([[2, 4, 5],
       [5, 7, 8]])

In [13]:
x1 = np.zeros((2,2))
x1

array([[0., 0.],
       [0., 0.]])

In [14]:
x2 = np.ones((2,2))
x2

array([[1., 1.],
       [1., 1.]])

In [16]:
x3 = np.full((2,2),3)
x3

array([[3, 3],
       [3, 3]])

In [18]:
arr = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [19]:
r2 = arr[1:3,:]
r2

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [20]:
#datatypes
d1=np.array([11,12])
d1.dtype

dtype('int32')

In [21]:
d2=np.array([1.0])
d2.dtype

dtype('float64')

In [22]:
d3=np.array([12,13],dtype=np.int64)
d3.dtype

dtype('int64')

In [23]:
d4=np.array([1.0],dtype=np.float64)
d4.dtype

dtype('float64')

In [24]:
d5=np.array([11,12],dtype=np.float64)
d5

array([11., 12.])

In [25]:
#arthmetic operation
x=np.array([[11,12],[21,22]],dtype=np.int64)
y=np.array([[1.2,4.5],[34.5,67.8]],dtype=np.float64)


In [26]:
#add
print(x+y)
print(np.add(x,y))

[[12.2 16.5]
 [55.5 89.8]]
[[12.2 16.5]
 [55.5 89.8]]


In [28]:
#subsract
print(x-y)
print(np.subtract(x,y))

[[  9.8   7.5]
 [-13.5 -45.8]]
[[  9.8   7.5]
 [-13.5 -45.8]]


In [29]:
#multiply
print(x*y)
print(np.multiply(x,y))

[[  13.2   54. ]
 [ 724.5 1491.6]]
[[  13.2   54. ]
 [ 724.5 1491.6]]


In [31]:
#devide
print(x/y)
print(np.divide(x,y))

[[9.16666667 2.66666667]
 [0.60869565 0.32448378]]
[[9.16666667 2.66666667]
 [0.60869565 0.32448378]]


In [32]:
#square root
np.sqrt(x)

array([[3.31662479, 3.46410162],
       [4.58257569, 4.69041576]])

In [34]:
#basic statiscal operation
ar1=10*np.random.randn(3,5)
ar1

array([[ -1.98943002,  11.90464865, -23.70858348,  -0.26048858,
          2.47924481],
       [ -4.97187559,   4.03086045,  -8.6828474 ,   7.87291616,
         11.00776609],
       [ -0.80850757,   1.69199106,   4.5996142 ,  -7.73973958,
          8.62819005]])

In [35]:
ar1.mean()

0.2702506176928774

In [36]:
ar1.mean(axis=1)

array([-2.31492172,  1.85136394,  1.27430963])

In [37]:
ar1.mean(axis=0)

array([-2.58993772,  5.87583339, -9.26393889, -0.04243733,  7.37173365])

In [38]:
ar1.sum()

4.053759265393161

In [39]:
np.median(ar1)

1.6919910623356635

In [41]:
#sorting
unsorted=np.random.randn(10)
unsorted

array([ 0.13351174,  1.87785222,  1.27246541,  1.09186885,  0.19268445,
        1.53086275, -1.53537623,  1.22688067, -1.92544619, -1.01342668])

In [42]:
s=unsorted
s.sort()
s

array([-1.92544619, -1.53537623, -1.01342668,  0.13351174,  0.19268445,
        1.09186885,  1.22688067,  1.27246541,  1.53086275,  1.87785222])

In [43]:
#finding unique elements
u = np.array([1,2,3,4,2,3,5])
print(np.unique(u))

[1 2 3 4 5]


In [45]:
s1 = np.array(['bulb','chair','lamb'])
s2 = np.array(['desk','bulb','chair'])
print(s1,s2)


['bulb' 'chair' 'lamb'] ['desk' 'bulb' 'chair']


In [50]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']
